version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "meli-proxy-db"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge