version: '3'

services:

  redis:
    image: redis:latest
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"


  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "meli-proxy-db"
    ports:
      - "13306:3306"



