spring:
  application:
    name: proxy

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

zuul:
  prefix: /api
  ignored-services: "*"
  routes:
    mercadolibre:
      path: /**
      serviceId: https://api.mercadolibre.com
      strip-prefix: false
